const mongoose = require('mongoose');
const Session = require('../models/sessionModel');
const FeeMonth = require('../models/FeeMonth');
const ClassMonthlyFee = require('../models/ClassMonthlyFee');
const StudentFeeLedger = require('../models/StudentFeeLedger');
const Student = require('../models/studentModel');

const objectId = (value) => (mongoose.Types.ObjectId.isValid(value) ? new mongoose.Types.ObjectId(value) : null);

async function resolveSessionContext(sessionId, schoolId) {
  if (!sessionId) {
    return { sessionId: null, sessionLabel: '' };
  }

  const id = objectId(sessionId);
  if (!id) {
    return { sessionId: null, sessionLabel: sessionId };
  }

  const schoolObjectId = objectId(schoolId);
  const query = { _id: id };
  if (schoolObjectId) {
    query.schoolId = schoolObjectId;
  } else if (schoolId) {
    query.schoolId = schoolId;
  }

  const session = await Session.findOne(query).lean();
  if (!session) {
    return { sessionId: null, sessionLabel: '' };
  }
  return { sessionId: session._id, sessionLabel: session.yearRange };
}

function recalculateLedgerAmounts(ledgerDoc) {
  const paidAmount = (ledgerDoc.payments || []).reduce((sum, payment) => sum + Number(payment.amount || 0), 0);
  ledgerDoc.paidAmount = paidAmount;
  ledgerDoc.dueAmount = Math.max(Number(ledgerDoc.totalAmount || 0) - paidAmount, 0);
  if (ledgerDoc.dueAmount === 0) {
    ledgerDoc.status = 'Paid';
  } else if (paidAmount > 0) {
    ledgerDoc.status = 'Partially Paid';
  } else {
    ledgerDoc.status = 'Due';
  }
}

async function fetchStudentsForClass({ schoolId, classId, sectionId }) {
  const filter = {
    schoolId: objectId(schoolId),
    classId: objectId(classId),
  };
  if (sectionId) {
    filter.$or = [
      { sectionId: objectId(sectionId) },
      { section: sectionId },
      { sectionName: sectionId },
    ];
  }

  return Student.find(filter)
    .select('_id name firstName lastName classId sectionId section sectionName academicYear rollNumber')
    .lean();
}

async function syncLedgersForClassMonthlyFee(classMonthlyFeeDoc, options = {}) {
  if (!classMonthlyFeeDoc) return;

  const schoolId = classMonthlyFeeDoc.schoolId;
  const sessionId = classMonthlyFeeDoc.sessionId;
  const classId = classMonthlyFeeDoc.classId;
  const sectionId = classMonthlyFeeDoc.sectionId;
  const monthId = classMonthlyFeeDoc.monthId;

  const month = options.month || (await FeeMonth.findById(monthId).lean());
  const students = await fetchStudentsForClass({ schoolId, classId, sectionId: sectionId || options.sectionId });

  const feeItems = (classMonthlyFeeDoc.feeItems || []).map((item) => ({
    feeHead: item.feeHead,
    amount: Number(item.amount || 0),
  }));
  const dueDate = month?.dueDate || null;

  for (const student of students) {
    const filter = {
      schoolId,
      sessionId,
      studentId: student._id,
      monthId,
    };

    const ledger = await StudentFeeLedger.findOne(filter);
    if (!ledger) {
      const payments = [];
      const newLedger = new StudentFeeLedger({
        schoolId,
        sessionId,
        sessionLabel: classMonthlyFeeDoc.sessionLabel,
        classId,
        sectionId,
        studentId: student._id,
        monthId,
        monthName: classMonthlyFeeDoc.monthName,
        dueDate,
        feeItems,
        totalAmount: Number(classMonthlyFeeDoc.totalAmount || 0),
        paidAmount: 0,
        dueAmount: Number(classMonthlyFeeDoc.totalAmount || 0),
        status: 'Due',
        payments,
        autoGeneratedFrom: classMonthlyFeeDoc._id,
        generatedAt: new Date(),
      });
      recalculateLedgerAmounts(newLedger);
      await newLedger.save();
      continue;
    }

    ledger.feeItems = feeItems;
    ledger.totalAmount = Number(classMonthlyFeeDoc.totalAmount || 0);
    if (dueDate) {
      ledger.dueDate = dueDate;
    }
    if (classMonthlyFeeDoc.monthName) {
      ledger.monthName = classMonthlyFeeDoc.monthName;
    }
    if (classMonthlyFeeDoc.sessionLabel) {
      ledger.sessionLabel = classMonthlyFeeDoc.sessionLabel;
    }
    ledger.autoGeneratedFrom = classMonthlyFeeDoc._id;
    ledger.generatedAt = new Date();
    recalculateLedgerAmounts(ledger);
    await ledger.save();
  }
}

async function removeLedgersForClassMonthlyFee(classMonthlyFeeDoc) {
  if (!classMonthlyFeeDoc) return;
  await StudentFeeLedger.deleteMany({
    schoolId: classMonthlyFeeDoc.schoolId,
    sessionId: classMonthlyFeeDoc.sessionId,
    classId: classMonthlyFeeDoc.classId,
    sectionId: classMonthlyFeeDoc.sectionId,
    monthId: classMonthlyFeeDoc.monthId,
    autoGeneratedFrom: classMonthlyFeeDoc._id,
  });
}

module.exports = {
  objectId,
  resolveSessionContext,
  recalculateLedgerAmounts,
  syncLedgersForClassMonthlyFee,
  removeLedgersForClassMonthlyFee,
};
