module.exports = [
  { name: 'HINDI', code: '01' },
  { name: 'ENGLISH', code: '02' },
  { name: 'MATHEMATICS', code: '03' },
  { name: 'SCIENCE', code: '04' },
  { name: 'SOCIAL STUDY', code: '05' },
  { name: 'SANSKRIT', code: '06' },
  { name: 'SOCIAL SCIENCE', code: '10' },
  { name: 'SONGS & STORIES', code: '11' },
  { name: 'MORAL SCIENCE', code: '12' },
  { name: 'MORAL VALUE', code: '13' },
  { name: 'E.V.S.', code: '14' },
  { name: 'PICTURE', code: '15' },
  { name: 'HOME SCIENCE', code: '16' },
  { name: 'BIOLOGY', code: '17' },
  { name: 'PHYSICS', code: '18' },
  { name: 'CHEMISTRY', code: '19' },
  { name: 'G.K.', code: '47' },
  { name: 'COMPUTER', code: '49' },
  { name: 'DRAWING', code: '50' },
  { name: 'P.T.', code: '51' },
  { name: 'REASONING', code: '30' },
  { name: 'CONVERSATION', code: '31' },
  { name: 'HYGIENE', code: '32' },
  { name: 'DANCE', code: '25' },
  { name: 'SINGING', code: '27' },
  { name: 'ACTIVITY', code: '28' },
  { name: 'ART & CRAFT', code: '52' },
  { name: 'Hindi Language', code: '80' },
  { name: 'Hindi Literatur', code: '81' },
  { name: 'Eng Language', code: '83' },
  { name: 'Eng Literature', code: '84' },
  { name: 'Eng Written', code: '85' },
  { name: 'English Oral', code: '86' },
  { name: 'Hindi Written', code: '87' },
  { name: 'Hindi Oral', code: '88' },
  { name: 'Math Oral', code: '89' },
  { name: 'Math Written', code: '90' },
  { name: 'G.K. Oral', code: '91' },
  { name: 'G.K. Written', code: '92' },
  { name: 'Craft', code: '93' },
  { name: 'Art', code: '94' }
];

