const DEFAULT_STUDENT_ID_LANDSCAPE_TEMPLATE = {
  version: '1.1',
  card: {
    widthMM: 86,
    heightMM: 54,
    paddingMM: 3,
    borderRadius: 6,
    backgroundColor: '#FFFFFF',
    borderColor: '#C41E3A',
    borderWidthMM: 0.4,
  },
  palette: {
    background: '#FFFFFF',
    primary: '#C41E3A',
    accent: '#F8B9C7',
    textPrimary: '#1F2937',
    textSecondary: '#52606D',
    textOnPrimary: '#FFFFFF',
    contactColor: '#C41E3A',
  },
  header: {
    heightRatio: 0.34,
    background: '#C41E3A',
    curve: {
      color: '#F8B9C7',
      heightRatio: 0.55,
      offset: -0.45,
      opacity: 1,
    },
    logo: {
      sizeRatio: 0.2,
      background: '#FFFFFF',
      borderColor: '#FFFFFF',
      borderWidthMM: 0.4,
      shape: 'circle',
    },
    text: {
      showSchoolName: true,
      showAddress: true,
      uppercase: true,
      nameFontSizePt: 11.2,
      addressFontSizePt: 7,
      color: '#FFFFFF',
    },
  },
  photo: {
    diameterRatio: 0.46,
    borderWidthMM: 0.7,
    borderColor: '#C41E3A',
    placeholderColor: '#FFFFFF',
    shadow: '0 8px 18px rgba(196, 30, 58, 0.18)',
  },
  nameSection: {
    fontSizePt: 11,
    fontWeight: 700,
    uppercase: true,
    textColor: '#C41E3A',
    letterSpacing: 0.6,
  },
  infoSection: {
    fontSizePt: 8.4,
    labelColor: '#52606D',
    valueColor: '#1F2937',
    rowGapPx: 6,
    columnGapPx: 18,
  },
  infoFields: [
    { key: 'classSection', label: 'Class' },
    { key: 'scholarNumber', label: 'Application No.' },
    { key: 'dateOfBirth', label: 'D.O.B' },
    { key: 'fatherName', label: "Father's Name", uppercaseValue: true },
     { key: 'address', label: 'Address', multiline: true },
    { key: 'bloodGroup', label: 'Blood Group' },
  ],
  footer: {
    contactFontSizePt: 8.6,
    contactPrefix: 'Contact No:',
    textColor: '#1F2937',
    contactColor: '#C41E3A',
    showSignature: true,
    signatureLabel: 'Principal',
    signatureBoxBackground: 'rgba(248, 185, 199, 0.28)',
    signatureBorderColor: 'rgba(196, 30, 58, 0.35)',
  },
  options: {
    allowBackgroundOverride: true,
    backgroundImageOpacity: 0.12,
  },
};

export default DEFAULT_STUDENT_ID_LANDSCAPE_TEMPLATE;
