const DEFAULT_STUDENT_ID_TEMPLATE = {
  version: '1.0',
  card: {
    widthMM: 54,
    heightMM: 86,
    borderRadius: 5,
    paddingMM: 3,
    backgroundColor: '#FFFFFF',
    borderColor: '#BF102A',
    borderWidthMM: 0.35,
  },
  palette: {
    background: '#FFFFFF',
    primary: '#BF102A',
    secondary: '#FCE4EA',
    accentDark: '#8D0E24',
    textPrimary: '#111827',
    textSecondary: '#374151',
    textOnPrimary: '#FFFFFF',
    contactColor: '#BF102A',
  },
  header: {
    heightRatio: 0.5,
    background: '#BF102A',
    swoosh: {
      color: '#F9CED7',
      accentColor: '#FF5F7D',
      opacity: 0.88,
      showAccent: true,
    },
    logo: {
      sizeRatio: 0.22,
      background: '#FFFFFF',
      borderColor: '#FFFFFF',
      borderWidthMM: 0.8,
    },
    text: {
      showSchoolName: true,
      showAddress: true,
      uppercase: true,
      nameFontSizePt: 9.8,
      addressFontSizePt: 6.2,
      color: '#FFFFFF',
    },
  },
  photo: {
    overlapRatio: 0.58,
    widthRatio: 0.38,
    aspectRatio: 1,
    shape: 'circle',
    frameColor: '#FFFFFF',
    frameWidthMM: 0.9,
    accentBorderWidthMM: 0.3,
    accentBorderColor: '#11182740',
    placeholderColor: '#F1F5F9',
  },
  nameSection: {
    fontSizePt: 9.5,
    fontWeight: 700,
    uppercase: true,
    background: '#FFFFFF',
    paddingMM: 1,
    borderRadius: 10,
    textAlign: 'center',
  },
  infoSection: {
    fontSizePt: 8.2,
  },
  infoFields: [
    { key: 'classSection', label: 'Class' },
    { key: 'scholarNumber', label: 'Scholar No.' },
    { key: 'dateOfBirth', label: 'D.O.B' },
    { key: 'bloodGroup', label: 'Blood Group' },
    { key: 'fatherName', label: "Father's Name", uppercaseValue: true },
    { key: 'mobile', label: 'Contact No.' },
    { key: 'address', label: 'Address', multiline: true },
    // { key: 'validTill', label: 'Session' },
  ],
  footer: {
    heightRatio: 0.18,
    background: '#FFFFFF',
    textColor: '#1F2937',
    contactFontSizePt: 8.2,
    contactColor: '#BF102A',
    showSignature: true,
    signatureLabel: 'Principal',
    signatureMaxWidthRatio: 0.36,
    signatureBackground: 'rgba(188, 16, 42, 0.12)',
    signatureBorderRadius: 12,
    signatureTextColor: '#0F172A',
  },
  options: {
    allowBackgroundOverride: true,
    showBodyGradient: true,
    colorVariants: [
      {
        name: 'Crimson',
        primary: '#BF102A',
        secondary: '#FCE4EA',
        accentDark: '#8D0E24',
        contactColor: '#BF102A',
      },
      {
        name: 'Royal Blue',
        primary: '#1D4ED8',
        secondary: '#DBEAFE',
        accentDark: '#1E3A8A',
        contactColor: '#1D4ED8',
      },
      {
        name: 'Emerald',
        primary: '#047857',
        secondary: '#D1FAE5',
        accentDark: '#065F46',
        contactColor: '#047857',
      },
    ],
  },
};

export default DEFAULT_STUDENT_ID_TEMPLATE;
