const DEFAULT_TEACHER_ID_TEMPLATE = {
  version: '1.0',
  card: {
    widthMM: 54,
    heightMM: 86,
    borderRadius: 5,
    paddingMM: 3,
    backgroundColor: '#FFFFFF',
    borderColor: '#1D4ED8',
    borderWidthMM: 0.4,
  },
  palette: {
    background: '#FFFFFF',
    primary: '#1D4ED8',
    secondary: '#DBEAFE',
    accentDark: '#1E3A8A',
    textPrimary: '#1F2937',
    textSecondary: '#4B5563',
    contactColor: '#1D4ED8',
  },
  header: {
    heightRatio: 0.45,
    background: '#1D4ED8',
    swoosh: {
      color: '#BFDBFE',
      accentColor: '#3B82F6',
      opacity: 0.85,
      showAccent: true,
    },
    logo: {
      sizeRatio: 0.20,
      background: '#FFFFFF',
      borderColor: '#FFFFFF',
      borderWidthMM: 0.6,
    },
    text: {
      showSchoolName: true,
      showAddress: true,
      uppercase: true,
      nameFontSizePt: 10,
      addressFontSizePt: 6.5,
      color: '#FFFFFF',
    },
  },
  photo: {
    overlapRatio: 0.56,
    widthRatio: 0.30,
    aspectRatio: 1,
    shape: 'circle',
    frameColor: '#FFFFFF',
    frameWidthMM: 0.7,
    accentBorderWidthMM: 0.25,
    accentBorderColor: '#1F293720',
    placeholderColor: '#F1F5F9',
  },
  nameSection: {
    fontSizePt: 10.2,
    fontWeight: 700,
    uppercase: true,
    background: '#FFFFFF',
    paddingMM: 1,
    borderRadius: 12,
    textAlign: 'center',
    borderColor: '#DBEAFE',
  },
  infoSection: {
    fontSizePt: 8.2,
    rowGapPx: 6,
    showDividers: true,
    labelColor: '#1E3A8A',
    valueColor: '#1F2937',
    labelFontSizePt: 7,
  },
  infoFields: [
    { key: 'designation', label: 'Designation', uppercaseValue: true },
    { key: 'department', label: 'Department', uppercaseValue: true },
    { key: 'employeeId', label: 'Teacher ID' },
    { key: 'mobile', label: 'Mobile' },
    { key: 'email', label: 'Email' },
    { key: 'bloodGroup', label: 'Blood Group', uppercaseValue: true },
  ],
  footer: {
    heightRatio: 0.18,
    background: '#FFFFFF',
    textColor: '#1F2937',
    contactFontSizePt: 8.2,
    contactColor: '#1D4ED8',
    showSignature: true,
    signatureLabel: 'Principal',
    signatureMaxWidthRatio: 0.42,
    signatureBackground: 'rgba(29, 78, 216, 0.12)',
    signatureTextColor: '#1F2937',
    signatureBorderColor: 'rgba(29, 78, 216, 0.22)',
    signatureBorderRadius: 12,
    showMohar: true,
    moharLabel: 'School Seal',
    moharBackground: '#FFFFFF',
    moharBorderColor: 'rgba(29, 78, 216, 0.24)',
  },
  options: {
    allowBackgroundOverride: true,
    showBodyGradient: true,
    backgroundImageOpacity: 0.15,
  },
};

export default DEFAULT_TEACHER_ID_TEMPLATE;
