const DEFAULT_STAFF_ID_LANDSCAPE_TEMPLATE = {
  version: '1.0',
  card: {
    widthMM: 86,
    heightMM: 54,
    paddingMM: 3,
    borderRadius: 6,
    backgroundColor: '#FFFFFF',
    borderColor: '#1D4ED8',
    borderWidthMM: 0.45,
  },
  palette: {
    background: '#FFFFFF',
    primary: '#1D4ED8',
    accent: '#BFDBFE',
    textPrimary: '#1F2937',
    textSecondary: '#1E3A8A',
    contactColor: '#1D4ED8',
  },
  header: {
    heightRatio: 0.34,
    background: '#1D4ED8',
    curve: {
      color: '#1D4ED8',
      heightRatio: 0.48,
      offset: -0.42,
      opacity: 0,
    },
    logo: {
      sizeRatio: 0.18,
      background: '#FFFFFF',
      borderColor: '#FFFFFF',
      borderWidthMM: 0.4,
      shape: 'circle',
    },
    text: {
      showSchoolName: true,
      showAddress: true,
      uppercase: true,
      nameFontSizePt: 11,
      addressFontSizePt: 7,
      color: '#FFFFFF',
    },
  },
  photo: {
    diameterRatio: 0.25,
    borderWidthMM: 0.25,
    borderColor: '#FFFFFF',
    placeholderColor: '#F1F5F9',
    shadow: '0 6px 14px rgba(29, 78, 216, 0.25)',
  },
  nameSection: {
    fontSizePt: 7,
    fontWeight: 800,
    uppercase: true,
    textColor: '#1D4ED8',
    letterSpacing: 0.6,
  },
  infoSection: {
    fontSizePt: 6,
    labelColor: '#1E3A8A',
    valueColor: '#1F2937',
    rowGapPx: 6,
    columnGapPx: 18,
  },
  infoFields: [
    { key: 'designation', label: 'Designation', uppercaseValue: true },
    { key: 'department', label: 'Department', uppercaseValue: true },
    { key: 'employeeId', label: 'Employee ID' },
    { key: 'mobile', label: 'Mobile' },
    { key: 'email', label: 'Email' },
    { key: 'bloodGroup', label: 'Blood Group', uppercaseValue: true },
  ],
  footer: {
    contactFontSizePt: 8,
    contactPrefix: 'Contact:',
    textColor: '#1F2937',
    contactColor: '#1D4ED8',
    showSignature: false,
    signatureLabel: 'Principal',
    signatureBoxBackground: '#FFFFFF',
    signatureBorderColor: 'rgba(29, 78, 216, 0.24)',
    signatureBorderRadius: 10,
    signatureTextColor: '#1E3A8A',
    showMohar: true,
    moharLabel: 'Principal',
  },
  options: {
    allowBackgroundOverride: true,
    backgroundImageOpacity: 0.15,
  },
};

export default DEFAULT_STAFF_ID_LANDSCAPE_TEMPLATE;
