const mongoose = require('mongoose');

const feeItemSchema = new mongoose.Schema({
  feeHead: {
    type: String,
    required: true,
    trim: true,
  },
  amount: {
    type: Number,
    required: true,
    min: 0,
  },
  description: {
    type: String,
    trim: true,
  },
}, { _id: false });

const classMonthlyFeeSchema = new mongoose.Schema({
  schoolId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'School',
    required: true,
    index: true,
  },
  sessionId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Session',
    required: true,
    index: true,
  },
  sessionLabel: {
    type: String,
    required: true,
    trim: true,
  },
  classId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Class',
    required: true,
    index: true,
  },
  sectionId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Section',
  },
  monthId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'FeeMonth',
    required: true,
    index: true,
  },
  monthName: {
    type: String,
    required: true,
    trim: true,
  },
  feeItems: {
    type: [feeItemSchema],
    default: [],
  },
  totalAmount: {
    type: Number,
    required: true,
    min: 0,
  },
  currency: {
    type: String,
    default: 'INR',
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Admin',
  },
  updatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Admin',
  },
  autoGeneratedAt: {
    type: Date,
  },
}, {
  timestamps: true,
});

classMonthlyFeeSchema.index({ schoolId: 1, sessionId: 1, classId: 1, sectionId: 1, monthId: 1 }, { unique: true });

module.exports = mongoose.model('ClassMonthlyFee', classMonthlyFeeSchema);
