const mongoose = require('mongoose');

const ledgerPaymentSchema = new mongoose.Schema({
  amount: {
    type: Number,
    required: true,
    min: 0,
  },
  mode: {
    type: String,
    enum: ['Cash', 'Cheque', 'UPI', 'Online', 'Bank Transfer', 'Card'],
    required: true,
  },
  receiptNumber: {
    type: String,
    trim: true,
    index: true,
  },
  receiptMetadata: {
    type: {
      receiptDate: {
        type: Date,
      },
      receiptTime: {
        type: String,
      },
      receiptGeneratedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Staff',
      },
    },
  },
  lateFeeComponent: {
    type: Number,
    default: 0,
    min: 0,
  },
  referenceNumber: {
    type: String,
    trim: true,
  },
  remark: {
    type: String,
    trim: true,
  },
  collectedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Staff',
  },
  paidOn: {
    type: Date,
    default: Date.now,
  },
}, { _id: false });

const ledgerFeeItemSchema = new mongoose.Schema({
  feeHead: {
    type: String,
    required: true,
    trim: true,
  },
  amount: {
    type: Number,
    required: true,
    min: 0,
  },
}, { _id: false });

const studentFeeLedgerSchema = new mongoose.Schema({
  schoolId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'School',
    required: true,
    index: true,
  },
  sessionId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Session',
    required: true,
    index: true,
  },
  sessionLabel: {
    type: String,
    required: true,
    trim: true,
  },
  classId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Class',
    required: true,
    index: true,
  },
  sectionId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Section',
  },
  studentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Student',
    required: true,
    index: true,
  },
  monthId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'FeeMonth',
    required: true,
    index: true,
  },
  monthName: {
    type: String,
    required: true,
    trim: true,
  },
  dueDate: {
    type: Date,
  },
  feeItems: {
    type: [ledgerFeeItemSchema],
    default: [],
  },
  totalAmount: {
    type: Number,
    required: true,
    min: 0,
  },
  paidAmount: {
    type: Number,
    default: 0,
    min: 0,
  },
  dueAmount: {
    type: Number,
    default: function defaultDue() {
      return this.totalAmount;
    },
    min: 0,
  },
  status: {
    type: String,
    enum: ['Due', 'Partially Paid', 'Paid'],
    default: 'Due',
  },
  payments: {
    type: [ledgerPaymentSchema],
    default: [],
  },
  autoGeneratedFrom: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'ClassMonthlyFee',
  },
  generatedAt: {
    type: Date,
  },
  notes: {
    type: String,
    trim: true,
  },
}, {
  timestamps: true,
});

studentFeeLedgerSchema.index({ schoolId: 1, sessionId: 1, studentId: 1, monthId: 1 }, { unique: true });

module.exports = mongoose.model('StudentFeeLedger', studentFeeLedgerSchema);
